/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAssistantRouteImport } from './routes/admin.assistant'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSignupRouteImport } from './routes/admin.signup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssistantRoute = AdminAssistantRouteImport.update({
  id: '/admin/assistant',
  path: '/admin/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin/signup',
  path: '/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chatbot'
    | '/admin/analytics'
    | '/admin/assistant'
    | '/admin/audit'
    | '/admin/events'
    | '/admin/login'
    | '/admin/signup'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chatbot'
    | '/admin/analytics'
    | '/admin/assistant'
    | '/admin/audit'
    | '/admin/events'
    | '/admin/login'
    | '/admin/signup'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/chatbot'
    | '/admin/analytics'
    | '/admin/assistant'
    | '/admin/audit'
    | '/admin/events'
    | '/admin/login'
    | '/admin/signup'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatbotRoute: typeof ChatbotRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAssistantRoute: typeof AdminAssistantRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSignupRoute: typeof AdminSignupRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assistant': {
      id: '/admin/assistant'
      path: '/admin/assistant'
      fullPath: '/admin/assistant'
      preLoaderRoute: typeof AdminAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatbotRoute: ChatbotRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAssistantRoute: AdminAssistantRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSignupRoute: AdminSignupRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
